[package]
name = "afkrip"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true

[dependencies]
clap = "3.2.22"
evdev = "0.12.0"
rand = "0.8.5"
rs-idle = { git = "https://git.hubto.org/public/rs-idle", version = "0.1.0" }
